name: SQL Linter
on:
  push:
    branches: main
jobs:
  sql_linter_test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: "actions/checkout@v3"
    - name: Install SQL linter
      run: |
       npm i -g sql-lint
       sql-lint RelationDB.sql
