name: TestCases

on:
  # оброка лише події типу push
  push:
    # обробка подій лише для гілки main
    branches:
      - main

jobs:
  TestCases:
    # використання Docker-image із вказаною версією ос
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      # клонування репозиторія для подальшої роботи з файлами на сервері
      # в каталозі $GITHUB_WORKSPACE
      uses: actions/checkout@v3
    - name: Compile
      # виконання декількох послідовних команд shell-інтерпретатором
      run: |
        cd $GITHUB_WORKSPACE/
        javac TestCases.java
