@startuml

title Activity Diagram

start
:Користувач бажає записати інформацію про сон;
:Програмний продукт відображає інтерфейс запису інформації про сон;
repeat
  :Користувач вводить дані про свій сон;
  if (Користувач ввів дані) then (так)
    :SleepTracker зберігає записані дані про сон;
    if (Збереження даних про сон успішне) then (так)
      :SleepTracker підтверджує успішне збереження даних;
      break
    else (ні)
      :SleepTracker повідомляє, що виникла помилка при збереженні даних;
    endif
  else (ні)
    :Програмний продукт чекає, поки користувач введе дані про сон;
  endif
repeat while (Збереження даних про сон не успішне)
stop
@enduml
